### ISSUE TITLE
Bug: ComponentMap off-by-one error

### ISSUE THREAD

**Issue by lewa-j** [Mgamerz/ME3Explorer#425]
When looking for references to an entry, there comes up stray entries with "Header: ComponentMap" in the list.  

Example: Mass Effect 2 original trilogy base game
Open in Package Editor file BioA_ProNor_600IllusiveMan.pcc
Entry `497 BIOG_PHM_General_F.PHM_GEN_dirt_01`
Find References shows `48 IllusiveManOffice_Prefab_Arc12: Header: ComponentMap`
When i look what components IllusiveManOffice_Prefab_Arc12 actually has, it's entry `498 PointLightComponent0`

I think ComponentMap contains not entry references but just Export indices, where 0 is the first export.

![img](https://github.com/user-attachments/assets/db834d27-137f-4abd-884f-a690116dd2e3)
![img2](https://github.com/user-attachments/assets/e18c15b0-028e-4f12-9554-57baef03afd3)

**Version information:**
Version 6.4 18.07.2024

**Comment by SirCxyrtyx** [comment]
> I think ComponentMap contains not entry references but just Export indices, where 0 is the first export.

You are correct. Thanks for reporting this. I think this went unnoticed for so long because almost all the modding activity these days is on the Legendary Edition versions of the games, which do not have ComponentMaps.

This is now fixed in the latest Nightly release.

Resolved by https://github.com/ME3Tweaks/LegendaryExplorer/commit/7ce2a6fbd25f079efee23ab8fe7bbd735d9ff7bc
